# One Half Light theme
foreground #383a42
background #fdfdfd
selection_foreground #383a42
selection_background #bfceff
cursor #0184bc
cursor_text_color #ffffff
cursor_shape beam
cursor_beam_thickness 2.5

color0 #383a42
color1 #e45649
color2 #50a14f
color3 #c18401
color4 #0184bc
color5 #a626a4
color6 #0997b3
color7 #fdfdfd
color8 #4f525e
color9 #e06c75
color10 #98c379
color11 #e5c07b
color12 #61afef
color13 #c678dd
color14 #56b6c2
color15 #ffffff

background_opacity 0.95

font_size 13
font_family JetBrains Mono

# CJK Fallback
symbol_map U+2E80-U+9FFF,U+F900-U+FAFF,U+FE30-U+FE4F,U+AC00-U+D7AF Sarasa Mono CL

window_padding_width 4

url_style single
