onboarding = false
[keys]
prefix = "ctrl+space"

# workspace 생성 popup을 위해 비워둠
new_workspace = ""

# workspace 간의 이동(즉시)
previous_workspace = "ctrl+shift+tab"
next_workspace = "ctrl+tab"
switch_workspace = ["cmd+1..9", "alt+1..9"]

# workspace 간의 이동(picker)
workspace_picker = ["prefix+shift+s"]
navigate_workspace_up = "up"
navigate_workspace_down = "down"

# agent 간의 이동(즉시)
previous_agent = "prefix+shift+comma"
next_agent = "prefix+shift+period"
focus_agent = "prefix+shift+1..9"

# agent 간의 이동(picker)
goto = ["prefix+shift+a"]

[[keys.command]]
key = "prefix+shift+n"
type = "popup"
description = "Select a directory and create a workspace"
width = "80%"
height = "60%"
command = '''
selected_dir="$(zoxide query -l | fzf --prompt='Workspace cwd> ')" || exit 0
[ -n "$selected_dir" ] || exit 0
"$HERDR_BIN_PATH" workspace create --cwd "$selected_dir" --focus >/dev/null
'''

[theme]
name = "one-light"
auto_switch = false

[theme.custom]
panel_bg = "#f5f5f5"
sidebar_bg = "#f5f5f5"
surface0 = "#f0f0f0"
surface1 = "#e5e5e5"
surface_dim = "#e5e5e5"
overlay0 = "#9d9d9f"
overlay1 = "#696c77"
subtext0 = "#696c77"
mauve = "#a626a4"
green = "#50a14f"
yellow = "#c18401"
red = "#e45649"
blue = "#0184bc"
teal = "#427b58"
peach = "#d65d0e"

[ui]
host_cursor = "native"
prompt_new_tab_name = false
