[colors]
background = "#fdfdfd"
foreground = "#383a42"

selection-background = "#bfceff"
selection-foreground = "#383a42"

tabs = "#5c6370"
tabs-active = "#383a42"
bar = "#eef1f4"
split = "#e5e7eb"

cursor = "#3a9a88"
vi-cursor = "#0184bc"

search-match-background = "#dbe5ff"
search-match-foreground = "#383a42"
search-focused-match-background = "#61afef"
search-focused-match-foreground = "#ffffff"

hint-foreground = "#383a42"
hint-background = "#e5c07b"

black = "#383a42"
red = "#e45649"
green = "#50a14f"
yellow = "#c18401"
blue = "#0184bc"
magenta = "#d65d0e"
cyan = "#427b58"
white = "#fdfdfd"

dim-black = "#5c6370"
dim-red = "#c9716b"
dim-green = "#7aa478"
dim-yellow = "#b3934d"
dim-blue = "#5f9fc9"
dim-magenta = "#c68156"
dim-cyan = "#698f73"
dim-white = "#f3f4f5"
dim-foreground = "#5c6370"

light-black = "#4f525e"
light-red = "#e06c75"
light-green = "#98c379"
light-yellow = "#e5c07b"
light-blue = "#61afef"
light-magenta = "#e78a4e"
light-cyan = "#689d6a"
light-white = "#ffffff"
light-foreground = "#2f3137"
