# Prefix.
set-option -g prefix C-a
set-option -g prefix2 None
unbind-key C-b
bind-key -N "Send prefix to nested tmux sessions" C-a send-prefix

# Sync status action.
bind-key -N "Toggle synchronized panes" S set-window-option synchronize-panes \; display-message "synchronize-panes toggled"
