from __future__ import annotations

from pathlib import Path, PurePosixPath

import pytest

from agent_core import cli, core
from agent_core.cli import main


def test_materialize_is_deterministic_and_marks_documents_and_skills() -> None:
    first = core.materialize("codex")
    assert first == core.materialize("codex")
    assert first[PurePosixPath(".agent-core-generated")] == b"agent-core v1\n"
    assert first[PurePosixPath("AGENTS.md")].startswith(b"<!-- Generated by agent-core v1; do not edit. -->")
    skill = first[PurePosixPath("skills/devils-advocate/SKILL.md")]
    assert skill.startswith(b"---\n")
    assert b"<!-- Generated by agent-core v1; do not edit. -->" in skill
    assert b"for coding agents." in skill


@pytest.mark.parametrize("runtime", core.RUNTIMES)
def test_every_runtime_explicitly_materializes_all_portable_skills(runtime: str) -> None:
    files = core.materialize(runtime)
    skills = {path.parts[1] for path in files if len(path.parts) > 2 and path.parts[0] == "skills"}
    assert skills == {
        "codebase-design", "code-review", "devils-advocate", "diagnosing-bugs",
        "domain-modeling", "grilling", "parallel-research-merge", "pi-agent",
        "prototype", "research", "resolving-merge-conflicts", "tdd", "wizard",
        "writing-for-agents",
    }


def test_runtime_document_layouts() -> None:
    pi = core.materialize("pi")
    assert PurePosixPath("AGENTS.md") in pi
    assert PurePosixPath("APPEND_SYSTEM.md") in pi
    assert b"# Operating invariants" not in pi[PurePosixPath("AGENTS.md")]
    assert b"# Operating invariants" in pi[PurePosixPath("APPEND_SYSTEM.md")]

    openclaw = core.materialize("openclaw")
    assert PurePosixPath("AGENTS.core.md") in openclaw
    assert PurePosixPath("AGENTS.md") not in openclaw


def test_render_requires_missing_or_empty_directory(tmp_path: Path) -> None:
    output = tmp_path / "output"
    core.render("pi", output)
    assert (output / "AGENTS.md").is_file()
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", output)

    real_output = tmp_path / "real-output"
    real_output.mkdir()
    linked_output = tmp_path / "linked-output"
    linked_output.symlink_to(real_output, target_is_directory=True)
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", linked_output)


def test_unknown_runtime_is_rejected() -> None:
    with pytest.raises(core.ValidationError, match="unknown runtime"):
        core.materialize("unknown")


def test_verify_install_reports_all_difference_kinds(tmp_path: Path) -> None:
    expected, actual = tmp_path / "expected", tmp_path / "actual"
    expected.mkdir()
    actual.mkdir()
    (expected / "missing").write_text("x")
    (actual / "unexpected").write_text("x")
    (expected / "type").write_text("x")
    (actual / "type").mkdir()
    (expected / "bytes").write_text("expected")
    (actual / "bytes").write_text("actual")
    (expected / "link").symlink_to("one")
    (actual / "link").symlink_to("two")
    differences = core.compare_trees(expected, actual)
    assert "missing: missing" in differences
    assert "unexpected: unexpected" in differences
    assert any(item.startswith("type differs: type") for item in differences)
    assert "bytes differ: bytes" in differences
    assert "symlink target differs: link" in differences


def test_cli_check_uses_golden_drift_fixture(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    assert main(["check"]) == 0
    schema = tmp_path / "schema"
    schema.mkdir()
    (schema / "golden-hashes.toml").write_text("[hashes]\nopenclaw = 'drift'\n")
    monkeypatch.setattr(cli, "resource_root", lambda: tmp_path)
    assert main(["check"]) == 1
