from __future__ import annotations

from pathlib import Path, PurePosixPath

import pytest
from agent_core import cli, core
from agent_core.cli import main


def write_skill(
    root: Path, directory_name: str, *, declared_name: str | None = None
) -> Path:
    skill = root / directory_name
    skill.mkdir(parents=True)
    name = declared_name or directory_name
    (skill / "SKILL.md").write_text(
        f"---\nname: {name}\ndescription: Runtime fixture.\n---\n\n# {name}\n"
    )
    return skill


def test_materialize_is_deterministic_and_marks_documents_and_skills() -> None:
    first = core.materialize("codex")
    assert first == core.materialize("codex")
    assert first[PurePosixPath(".agent-core-generated")] == b"agent-core v1\n"
    assert first[PurePosixPath("AGENTS.md")].startswith(
        b"<!-- Generated by agent-core v1; do not edit. -->"
    )
    skill = first[PurePosixPath("skills/code-review/SKILL.md")]
    assert skill.startswith(b"---\n")
    assert b"<!-- Generated by agent-core v1; do not edit. -->" in skill
    assert b"Two-axis review" in skill


@pytest.mark.parametrize("runtime", core.RUNTIMES)
def test_every_runtime_explicitly_materializes_all_portable_skills(
    runtime: str,
) -> None:
    files = core.materialize(runtime)
    skills = {
        path.parts[1]
        for path in files
        if len(path.parts) > 2 and path.parts[0] == "skills"
    }
    assert skills == {
        "codebase-design",
        "code-review",
        "diagnosing-bugs",
        "domain-modeling",
        "grilling",
        "prototype",
        "research",
        "resolving-merge-conflicts",
        "tdd",
        "wizard",
        "writing-for-agents",
    }


def test_runtime_document_layouts() -> None:
    pi = core.materialize("pi")
    assert PurePosixPath("AGENTS.md") in pi
    assert PurePosixPath("APPEND_SYSTEM.md") in pi
    assert b"# Operating invariants" not in pi[PurePosixPath("AGENTS.md")]
    assert b"# Operating invariants" in pi[PurePosixPath("APPEND_SYSTEM.md")]

    openclaw = core.materialize("openclaw")
    assert PurePosixPath("AGENTS.core.md") in openclaw
    assert PurePosixPath("AGENTS.md") not in openclaw


def test_render_requires_missing_or_empty_directory(tmp_path: Path) -> None:
    output = tmp_path / "output"
    core.render("pi", output)
    assert (output / "AGENTS.md").is_file()
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", output)

    real_output = tmp_path / "real-output"
    real_output.mkdir()
    linked_output = tmp_path / "linked-output"
    linked_output.symlink_to(real_output, target_is_directory=True)
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", linked_output)


def test_unknown_runtime_is_rejected() -> None:
    with pytest.raises(core.ValidationError, match="unknown runtime"):
        core.materialize("unknown")


def test_runtime_skill_roots_are_merged_and_deterministic(tmp_path: Path) -> None:
    first_root = tmp_path / "first"
    second_root = tmp_path / "second"
    first_skill = write_skill(first_root, "runtime-one")
    write_skill(second_root, "runtime-two")
    (first_skill / "reference.md").write_bytes(b"runtime reference\n")

    first = core.materialize("codex", [first_root, second_root])
    second = core.materialize("codex", [first_root, second_root])

    assert first == second
    assert core.output_hash(first) == core.output_hash(second)
    assert (
        b"Generated by agent-core"
        in first[PurePosixPath("skills/runtime-one/SKILL.md")]
    )
    assert (
        first[PurePosixPath("skills/runtime-one/reference.md")]
        == b"runtime reference\n"
    )
    assert PurePosixPath("skills/runtime-two/SKILL.md") in first


def test_runtime_skill_cannot_replace_portable_skill(tmp_path: Path) -> None:
    runtime_root = tmp_path / "runtime"
    write_skill(runtime_root, "tdd")

    with pytest.raises(core.ValidationError, match="duplicate skill name: tdd"):
        core.materialize("codex", [runtime_root])


def test_runtime_skill_roots_reject_duplicate_names(tmp_path: Path) -> None:
    first_root = tmp_path / "first"
    second_root = tmp_path / "second"
    write_skill(first_root, "duplicate")
    write_skill(second_root, "duplicate")

    with pytest.raises(core.ValidationError, match="duplicate skill name: duplicate"):
        core.materialize("codex", [first_root, second_root])


def test_runtime_skill_requires_valid_document(tmp_path: Path) -> None:
    missing_root = tmp_path / "missing"
    (missing_root / "missing-document").mkdir(parents=True)
    with pytest.raises(core.ValidationError, match="missing SKILL.md"):
        core.materialize("codex", [missing_root])

    invalid_root = tmp_path / "invalid"
    invalid_skill = invalid_root / "invalid-frontmatter"
    invalid_skill.mkdir(parents=True)
    (invalid_skill / "SKILL.md").write_text("# Missing frontmatter\n")
    with pytest.raises(
        core.ValidationError, match="missing or invalid SKILL.md frontmatter"
    ):
        core.materialize("codex", [invalid_root])

    mismatch_root = tmp_path / "mismatch"
    write_skill(mismatch_root, "directory-name", declared_name="declared-name")
    with pytest.raises(
        core.ValidationError, match="skill directory-name/name mismatch"
    ):
        core.materialize("codex", [mismatch_root])


def test_runtime_skill_roots_reject_symlinks(tmp_path: Path) -> None:
    real_root = tmp_path / "real"
    skill = write_skill(real_root, "linked-content")
    (skill / "target.md").write_text("target\n")
    (skill / "linked.md").symlink_to(skill / "target.md")

    with pytest.raises(core.ValidationError, match="unsafe skill source path"):
        core.materialize("codex", [real_root])

    linked_root = tmp_path / "linked-root"
    linked_root.symlink_to(real_root, target_is_directory=True)
    with pytest.raises(core.ValidationError, match="unsafe runtime skill root"):
        core.materialize("codex", [linked_root])


def test_cli_accepts_repeated_runtime_skill_roots(tmp_path: Path) -> None:
    first_root = tmp_path / "first"
    second_root = tmp_path / "second"
    write_skill(first_root, "runtime-one")
    write_skill(second_root, "runtime-two")
    output = tmp_path / "output"

    assert (
        main(
            [
                "render",
                "--runtime",
                "codex",
                "--runtime-skill-root",
                str(first_root),
                "--runtime-skill-root",
                str(second_root),
                "--output",
                str(output),
            ]
        )
        == 0
    )
    assert (output / "skills/runtime-one/SKILL.md").is_file()
    assert (output / "skills/runtime-two/SKILL.md").is_file()


def test_cli_help_describes_commands_and_render_arguments(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(SystemExit) as top_level_exit:
        main(["--help"])
    assert top_level_exit.value.code == 0
    top_level_help = capsys.readouterr().out
    assert "Render and validate shared instructions and skills" in top_level_help
    assert "render" in top_level_help
    assert "check" in top_level_help
    assert "verify-install" in top_level_help
    assert "examples:" in top_level_help

    with pytest.raises(SystemExit) as render_exit:
        main(["render", "--help"])
    assert render_exit.value.code == 0
    render_help = capsys.readouterr().out
    normalized_render_help = " ".join(render_help.split())
    assert "optional runtime-specific skills" in normalized_render_help
    assert "--runtime-skill-root" in render_help
    assert "Missing or empty directory" in normalized_render_help


def test_verify_install_reports_all_difference_kinds(tmp_path: Path) -> None:
    expected, actual = tmp_path / "expected", tmp_path / "actual"
    expected.mkdir()
    actual.mkdir()
    (expected / "missing").write_text("x")
    (actual / "unexpected").write_text("x")
    (expected / "type").write_text("x")
    (actual / "type").mkdir()
    (expected / "bytes").write_text("expected")
    (actual / "bytes").write_text("actual")
    (expected / "link").symlink_to("one")
    (actual / "link").symlink_to("two")
    differences = core.compare_trees(expected, actual)
    assert "missing: missing" in differences
    assert "unexpected: unexpected" in differences
    assert any(item.startswith("type differs: type") for item in differences)
    assert "bytes differ: bytes" in differences
    assert "symlink target differs: link" in differences


def test_cli_check_uses_golden_drift_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert main(["check"]) == 0
    schema = tmp_path / "schema"
    schema.mkdir()
    (schema / "golden-hashes.toml").write_text("[hashes]\nopenclaw = 'drift'\n")
    monkeypatch.setattr(cli, "resource_root", lambda: tmp_path)
    assert main(["check"]) == 1
