from __future__ import annotations

from pathlib import Path, PurePosixPath

import pytest
from agent_core import cli, core
from agent_core.cli import main


def test_materialize_is_deterministic_and_marks_documents_and_skills() -> None:
    first = core.materialize("codex")
    assert first == core.materialize("codex")
    assert first[PurePosixPath(".agent-core-generated")] == b"agent-core v1\n"
    assert first[PurePosixPath("AGENTS.md")].startswith(
        b"<!-- Generated by agent-core v1; do not edit. -->"
    )
    skill = first[PurePosixPath("skills/code-review/SKILL.md")]
    assert skill.startswith(b"---\n")
    assert b"<!-- Generated by agent-core v1; do not edit. -->" in skill
    assert b"Two-axis review" in skill


@pytest.mark.parametrize(
    ("runtime", "additional_skills"),
    [
        ("openclaw", set()),
        ("claude", set()),
        ("codex", {"devils-advocate", "parallel-research-merge"}),
        ("pi", {"devils-advocate", "parallel-research-merge", "pi-agent"}),
    ],
)
def test_every_runtime_materializes_its_selected_shared_skills(
    runtime: str, additional_skills: set[str]
) -> None:
    files = core.materialize(runtime)
    skills = {
        path.parts[1]
        for path in files
        if len(path.parts) > 2 and path.parts[0] == "skills"
    }
    common_skills = {
        "codebase-design",
        "code-review",
        "diagnosing-bugs",
        "domain-modeling",
        "grilling",
        "prototype",
        "research",
        "resolving-merge-conflicts",
        "tdd",
        "wizard",
        "writing-for-agents",
    }
    assert skills == common_skills | additional_skills


def test_runtime_document_layouts() -> None:
    pi = core.materialize("pi")
    assert PurePosixPath("AGENTS.md") in pi
    assert PurePosixPath("APPEND_SYSTEM.md") in pi
    assert b"# Operating invariants" not in pi[PurePosixPath("AGENTS.md")]
    assert b"# Operating invariants" in pi[PurePosixPath("APPEND_SYSTEM.md")]

    openclaw = core.materialize("openclaw")
    assert PurePosixPath("AGENTS.core.md") in openclaw
    assert PurePosixPath("AGENTS.md") not in openclaw


def test_render_requires_missing_or_empty_directory(tmp_path: Path) -> None:
    output = tmp_path / "output"
    core.render("pi", output)
    assert (output / "AGENTS.md").is_file()
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", output)

    real_output = tmp_path / "real-output"
    real_output.mkdir()
    linked_output = tmp_path / "linked-output"
    linked_output.symlink_to(real_output, target_is_directory=True)
    with pytest.raises(core.ValidationError, match="missing or empty"):
        core.render("pi", linked_output)


def test_unknown_runtime_is_rejected() -> None:
    with pytest.raises(core.ValidationError, match="unknown runtime"):
        core.materialize("unknown")


def test_cli_help_describes_commands_and_render_arguments(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(SystemExit) as top_level_exit:
        main(["--help"])
    assert top_level_exit.value.code == 0
    top_level_help = capsys.readouterr().out
    assert "Render and validate shared instructions and skills" in top_level_help
    assert "render" in top_level_help
    assert "check" in top_level_help
    assert "verify-install" in top_level_help
    assert "examples:" in top_level_help

    with pytest.raises(SystemExit) as render_exit:
        main(["render", "--help"])
    assert render_exit.value.code == 0
    render_help = capsys.readouterr().out
    normalized_render_help = " ".join(render_help.split())
    assert "selected shared skills" in normalized_render_help
    assert "--runtime-skill-root" not in render_help
    assert "Missing or empty directory" in normalized_render_help


def test_verify_install_reports_all_difference_kinds(tmp_path: Path) -> None:
    expected, actual = tmp_path / "expected", tmp_path / "actual"
    expected.mkdir()
    actual.mkdir()
    (expected / "missing").write_text("x")
    (actual / "unexpected").write_text("x")
    (expected / "type").write_text("x")
    (actual / "type").mkdir()
    (expected / "bytes").write_text("expected")
    (actual / "bytes").write_text("actual")
    (expected / "link").symlink_to("one")
    (actual / "link").symlink_to("two")
    differences = core.compare_trees(expected, actual)
    assert "missing: missing" in differences
    assert "unexpected: unexpected" in differences
    assert any(item.startswith("type differs: type") for item in differences)
    assert "bytes differ: bytes" in differences
    assert "symlink target differs: link" in differences


def test_cli_check_uses_golden_drift_fixture(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    assert main(["check"]) == 0
    schema = tmp_path / "schema"
    schema.mkdir()
    (schema / "golden-hashes.toml").write_text("[hashes]\nopenclaw = 'drift'\n")
    monkeypatch.setattr(cli, "resource_root", lambda: tmp_path)
    assert main(["check"]) == 1
