{
  config,
  lib,
  pkgs,
  username,
  homeDirectory,
  themeExports,
  isWSL ? false,
  ...
}:

let
  cfg = config.modules.orca;

  ghosttyThemeFile = themeExports.file "ghostty" "${config.modules.commonTheme}.conf";
  ghosttyThemeConfig = builtins.readFile ghosttyThemeFile;
  orcaFontFamilies = [ cfg.fontFamily ] ++ cfg.fontFallbackFamilies;
  orcaTerminalFontFamily = lib.concatStringsSep ''", "'' orcaFontFamilies;
  ghosttyFontFamilyConfig = lib.concatMapStringsSep "\n" (
    font: ''font-family = "${font}"''
  ) orcaFontFamilies;

  orcaGhosttyImportConfig = ''
    # Generated by Home Manager for Orca's Ghostty importer.
    # Source theme: themes/exports/ghostty/${config.modules.commonTheme}.conf
    ${ghosttyThemeConfig}

    background-opacity = ${toString cfg.backgroundOpacity}
    unfocused-split-opacity = ${toString cfg.inactivePaneOpacity}
    font-size = ${toString cfg.fontSize}
    ${ghosttyFontFamilyConfig}
    font-weight = ${toString cfg.fontWeight}
    cursor-style = ${cfg.cursorStyle}
    cursor-style-blink = ${if cfg.cursorBlink then "true" else "false"}
  '';

  parseGhosttyLine =
    line:
    let
      trimmed = lib.trim line;
      match = builtins.match "([^=]+)=(.*)" trimmed;
    in
    if trimmed == "" || lib.hasPrefix "#" trimmed || match == null then
      null
    else
      {
        key = lib.trim (builtins.elemAt match 0);
        value = lib.trim (builtins.elemAt match 1);
      };

  ghosttyEntries = builtins.filter (entry: entry != null) (
    builtins.map parseGhosttyLine (lib.splitString "\n" ghosttyThemeConfig)
  );

  directColorKeys = {
    background = "background";
    foreground = "foreground";
    "cursor-color" = "cursor";
    "cursor-text" = "cursorAccent";
    "selection-background" = "selectionBackground";
    "selection-foreground" = "selectionForeground";
  };

  directColorOverrides = builtins.listToAttrs (
    builtins.filter (entry: entry != null) (
      builtins.map (
        entry:
        if builtins.hasAttr entry.key directColorKeys then
          {
            name = directColorKeys.${entry.key};
            inherit (entry) value;
          }
        else
          null
      ) ghosttyEntries
    )
  );

  paletteColorKeys = {
    "0" = "black";
    "1" = "red";
    "2" = "green";
    "3" = "yellow";
    "4" = "blue";
    "5" = "magenta";
    "6" = "cyan";
    "7" = "white";
    "8" = "brightBlack";
    "9" = "brightRed";
    "10" = "brightGreen";
    "11" = "brightYellow";
    "12" = "brightBlue";
    "13" = "brightMagenta";
    "14" = "brightCyan";
    "15" = "brightWhite";
  };

  parsePaletteEntry =
    entry:
    let
      match = builtins.match "([0-9]+)=(#[0-9a-fA-F]+)" entry.value;
      index = if match == null then null else builtins.elemAt match 0;
    in
    if entry.key != "palette" || match == null || !(builtins.hasAttr index paletteColorKeys) then
      null
    else
      {
        name = paletteColorKeys.${index};
        value = builtins.elemAt match 1;
      };

  paletteColorOverrides = builtins.listToAttrs (
    builtins.filter (entry: entry != null) (builtins.map parsePaletteEntry ghosttyEntries)
  );

  terminalColorOverrides = directColorOverrides // paletteColorOverrides;
  terminalDividerColor = terminalColorOverrides.selectionBackground or "#474747";
  orcaTerminalThemeId = "ghostty:${config.modules.commonTheme}";
  orcaTerminalThemeSelection = "custom:${orcaTerminalThemeId}";
  orcaTerminalThemeName =
    if config.modules.commonTheme == "vira-graphene" then
      "Vira Graphene"
    else
      config.modules.commonTheme;
  orcaTerminalTheme = {
    id = orcaTerminalThemeId;
    name = orcaTerminalThemeName;
    source = "ghostty";
    mode = "dark";
    terminal = terminalColorOverrides;
    importedAt = "2026-06-29T00:00:00.000Z";
    sourceLabel = "themes/exports/ghostty/${config.modules.commonTheme}.conf";
  };

  windowsRoamingPath = "/mnt/c/Users/${cfg.windowsUsername}/AppData/Roaming";
  windowsOrcaDataPath = "${windowsRoamingPath}/orca/orca-data.json";
  darwinOrcaDataPath = "${homeDirectory}/Library/Application Support/orca/orca-data.json";
  orcaMergeFilter = ./files/merge-orca-data.jq;

  wslSettings = lib.optionalAttrs (isWSL && cfg.wslDistro != "") {
    terminalWindowsShell = "wsl.exe";
    terminalWindowsWslDistro = cfg.wslDistro;
    localWindowsRuntimeDefault = {
      kind = "wsl";
      distro = cfg.wslDistro;
    };
  };

  orcaSettingsPatch = {
    terminalFontSize = cfg.fontSize;
    terminalFontFamily = orcaTerminalFontFamily;
    terminalFontWeight = cfg.fontWeight;
    terminalLineHeight = cfg.lineHeight;
    terminalLigatures = cfg.ligatures;
    terminalCursorStyle = cfg.cursorStyle;
    terminalCursorStyleDefaultedToBlock = false;
    terminalCursorBlink = cfg.cursorBlink;
    terminalThemeDark = orcaTerminalThemeSelection;
    terminalThemeLight = orcaTerminalThemeSelection;
    terminalCustomThemes = [ orcaTerminalTheme ];
    terminalDividerColorDark = terminalDividerColor;
    terminalDividerColorLight = terminalDividerColor;
    terminalBackgroundOpacity = cfg.backgroundOpacity;
    terminalInactivePaneOpacity = cfg.inactivePaneOpacity;
    terminalActivePaneOpacity = cfg.activePaneOpacity;
    terminalUseSeparateLightTheme = false;
    inherit terminalColorOverrides;
  }
  // wslSettings
  // cfg.extraSettings;

  orcaDataPatch = {
    settings = orcaSettingsPatch;
    ui = cfg.uiSettings;
  };

  orcaDataPatchFile = pkgs.writeText "orca-data-patch.json" (builtins.toJSON orcaDataPatch);

  mergeOrcaDataScript = ''
    if [ ! -f "$orca_data" ]; then
      echo "Skipping Orca $orca_target config: $orca_data does not exist"
      exit 0
    fi

    if [ ! -f "$orca_data.pre-nix-orca.bak" ]; then
      cp "$orca_data" "$orca_data.pre-nix-orca.bak"
    fi

    tmp="$orca_data.tmp.$$"
    if ${pkgs.jq}/bin/jq --slurpfile patch "${orcaDataPatchFile}" \
      -f "${orcaMergeFilter}" "$orca_data" > "$tmp"; then
      if cmp -s "$tmp" "$orca_data"; then
        rm -f "$tmp"
      else
        mv "$tmp" "$orca_data"
      fi
    else
      rm -f "$tmp"
      exit 1
    fi
  '';

  darwinActivationScript = ''
    orca_target="macOS"
    orca_data="${darwinOrcaDataPath}"

    if command -v pgrep >/dev/null 2>&1 && pgrep -x Orca >/dev/null 2>&1; then
      echo "Cannot update Orca settings while Orca is running. Quit Orca and rerun home-manager switch to apply terminal settings." >&2
      exit 1
    fi

    ${mergeOrcaDataScript}
  '';

  windowsActivationScript = ''
    roaming_dir="${windowsRoamingPath}"
    if [ ! -d "$roaming_dir" ]; then
      echo "Skipping Orca Windows config: $roaming_dir does not exist"
      exit 0
    fi

    orca_target="Windows"
    orca_data="${windowsOrcaDataPath}"

    if command -v powershell.exe >/dev/null 2>&1; then
      if powershell.exe -NoProfile -Command "if (Get-Process -Name Orca -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }" >/dev/null 2>&1; then
        echo "Cannot update Orca settings while Orca is running. Quit Orca and rerun home-manager switch to apply terminal settings." >&2
        exit 1
      fi
    fi

    ${mergeOrcaDataScript}
  '';
in
{
  options.modules.orca = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable Orca terminal settings integration.";
    };

    windowsUsername = lib.mkOption {
      type = lib.types.str;
      default = username;
      description = "Windows user profile name used when configuring Orca from WSL.";
    };

    wslDistro = lib.mkOption {
      type = lib.types.str;
      default = "Ubuntu";
      description = "WSL distro name Orca should use for new terminals and project runtime.";
    };

    fontFamily = lib.mkOption {
      type = lib.types.str;
      default = "JetBrains Mono";
      description = "Primary Orca terminal font family.";
    };

    fontFallbackFamilies = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "Sarasa Mono CL"
        "D2Coding"
      ];
      description = "Fallback Orca terminal font families for Korean and other CJK glyphs.";
    };

    fontSize = lib.mkOption {
      type = lib.types.number;
      default = 14;
      description = "Orca terminal font size.";
    };

    fontWeight = lib.mkOption {
      type = lib.types.int;
      default = 400;
      description = "Orca terminal font weight.";
    };

    lineHeight = lib.mkOption {
      type = lib.types.number;
      default = 1;
      description = "Orca terminal line height.";
    };

    ligatures = lib.mkOption {
      type = lib.types.enum [
        "auto"
        "on"
        "off"
      ];
      default = "auto";
      description = "Orca terminal ligature mode.";
    };

    cursorStyle = lib.mkOption {
      type = lib.types.enum [
        "bar"
        "block"
        "underline"
      ];
      default = "bar";
      description = "Orca terminal cursor style.";
    };

    cursorBlink = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether the Orca terminal cursor blinks.";
    };

    backgroundOpacity = lib.mkOption {
      type = lib.types.number;
      default = 1;
      description = "Orca terminal background opacity.";
    };

    inactivePaneOpacity = lib.mkOption {
      type = lib.types.number;
      default = 0.9;
      description = "Opacity for inactive Orca terminal panes.";
    };

    activePaneOpacity = lib.mkOption {
      type = lib.types.number;
      default = 1;
      description = "Opacity for active Orca terminal panes.";
    };

    extraSettings = lib.mkOption {
      type = lib.types.attrs;
      default = { };
      description = "Additional values to merge into Orca's settings object.";
    };

    uiSettings = lib.mkOption {
      type = lib.types.attrs;
      default = { };
      description = "Values to merge into Orca's ui object.";
    };

    applyWindowsSettings = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "When running under WSL, merge terminal settings into Windows Orca data.";
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      {
        xdg.configFile."orca/ghostty-import.conf".text = orcaGhosttyImportConfig;
      }

      (lib.mkIf (isWSL && cfg.applyWindowsSettings) {
        home.activation.orcaWindowsConfig = lib.hm.dag.entryAfter [
          "writeBoundary"
        ] windowsActivationScript;
      })

      (lib.mkIf pkgs.stdenv.isDarwin {
        home.activation.orcaDarwinConfig = lib.hm.dag.entryAfter [
          "writeBoundary"
        ] darwinActivationScript;
      })
    ]
  );
}
