-- Auto-generated from themes/core/one-half-light.yaml
-- Template: neovim-official-highlight-template v1
local M = {}

local p = {
  bg = "#fdfdfd",
  bg_float = "#f5f5f5",
  bg_alt = "#f0f0f0",
  border = "#e5e5e5",
  hover = "#eeeeee",
  selection = "#d9e2fe",
  search = "#f5e9d3",
  search_active = "#93cae2",
  fg = "#383a42",
  fg_muted = "#9d9d9f",
  fg_bright = "#383a42",
  comment = "#a0a1a7",
  red = "#e45649",
  orange = "#d65d0e",
  yellow = "#c18401",
  green = "#50a14f",
  cyan = "#427b58",
  blue = "#0184bc",
  magenta = "#a626a4",
  pink = "#e06c75",
  linenr = "#a0a1a7",
  diff_add_bg = "#deecde",
  diff_change_bg = "#f2e7d0",
  diff_delete_bg = "#f8dfdd",
  diff_text_bg = "#f7eddb",
  cursor = "#0184bc",
  none = "NONE",
}

function M.setup()
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.o.background = "light"
  vim.g.colors_name = "one_half_light"

  local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
  end

  -- UI
  hl("Normal", { fg = p.fg, bg = p.bg })
  hl("NormalNC", { fg = p.fg_muted, bg = p.bg })
  hl("NormalFloat", { fg = p.fg, bg = p.bg_float })
  hl("FloatBorder", { fg = p.border, bg = p.bg_float })
  hl("FloatTitle", { fg = p.blue, bg = p.bg_float, bold = true })
  hl("FloatFooter", { fg = p.comment, bg = p.bg_float })
  hl("Cursor", { fg = p.cursor, reverse = true })
  hl("lCursor", { fg = p.cursor, reverse = true })
  hl("CursorIM", { fg = p.cursor, reverse = true })
  hl("TermCursor", { fg = p.cursor, reverse = true })
  hl("CursorLine", { bg = p.bg_alt })
  hl("CursorColumn", { bg = p.bg_alt })
  hl("ColorColumn", { bg = p.bg_alt })
  hl("LineNr", { fg = p.linenr })
  hl("LineNrAbove", { fg = p.linenr })
  hl("LineNrBelow", { fg = p.linenr })
  hl("CursorLineNr", { fg = p.fg_bright, bold = true })
  hl("SignColumn", { bg = p.bg })
  hl("CursorLineSign", { fg = p.fg_bright, bg = p.bg_alt })
  hl("FoldColumn", { fg = p.linenr, bg = p.bg })
  hl("CursorLineFold", { fg = p.fg_bright, bg = p.bg_alt })
  hl("WinSeparator", { fg = p.border })
  hl("VertSplit", { fg = p.border })
  hl("StatusLine", { fg = p.fg, bg = p.bg_float })
  hl("StatusLineNC", { fg = p.fg_muted, bg = p.bg_alt })
  hl("StatusLineTerm", { fg = p.fg, bg = p.bg_float })
  hl("StatusLineTermNC", { fg = p.fg_muted, bg = p.bg_alt })
  hl("TabLine", { fg = p.fg_muted, bg = p.bg_alt })
  hl("TabLineFill", { bg = p.bg_alt })
  hl("TabLineSel", { fg = p.fg, bg = p.bg, bold = true })
  hl("WinBar", { fg = p.fg, bg = p.bg_float })
  hl("WinBarNC", { fg = p.fg_muted, bg = p.bg_alt })
  hl("Pmenu", { fg = p.fg, bg = p.bg_float })
  hl("PmenuSel", { bg = p.selection })
  hl("PmenuKind", { fg = p.orange, bg = p.bg_float })
  hl("PmenuKindSel", { fg = p.orange, bg = p.selection })
  hl("PmenuExtra", { fg = p.comment, bg = p.bg_float })
  hl("PmenuExtraSel", { fg = p.comment, bg = p.selection })
  hl("PmenuSbar", { bg = p.bg_alt })
  hl("PmenuThumb", { bg = p.border })
  hl("PmenuMatch", { fg = p.blue, bg = p.bg_float, bold = true })
  hl("PmenuMatchSel", { fg = p.blue, bg = p.selection, bold = true })
  hl("ComplMatchIns", { fg = p.blue, bold = true })
  hl("Visual", { bg = p.selection })
  hl("VisualNOS", { bg = p.selection })
  hl("Search", { bg = p.search })
  hl("CurSearch", { bg = p.search_active, bold = true })
  hl("IncSearch", { bg = p.search_active })
  hl("Substitute", { fg = p.fg, bg = p.search_active, bold = true })
  hl("MatchParen", { fg = p.blue, underline = true })
  hl("QuickFixLine", { bg = p.hover })
  hl("Folded", { fg = p.comment, bg = p.bg_float })
  hl("Directory", { fg = p.blue })
  hl("Title", { fg = p.blue, bold = true })
  hl("Question", { fg = p.green })
  hl("MoreMsg", { fg = p.green })
  hl("ModeMsg", { fg = p.fg, bold = true })
  hl("MsgArea", { fg = p.fg, bg = p.bg })
  hl("MsgSeparator", { fg = p.border, bg = p.bg })
  hl("WarningMsg", { fg = p.yellow, bold = true })
  hl("ErrorMsg", { fg = p.red, bold = true })
  hl("NonText", { fg = p.border })
  hl("EndOfBuffer", { fg = p.bg_float })
  hl("SpecialKey", { fg = p.border })
  hl("Whitespace", { fg = p.border })
  hl("Conceal", { fg = p.comment })
  hl("WildMenu", { bg = p.selection })
  hl("SnippetTabstop", { bg = p.selection })
  hl("SpellBad", { undercurl = true, sp = p.red })
  hl("SpellCap", { undercurl = true, sp = p.yellow })
  hl("SpellRare", { undercurl = true, sp = p.orange })
  hl("SpellLocal", { undercurl = true, sp = p.cyan })
  hl("DiffAdd", { bg = p.diff_add_bg })
  hl("DiffChange", { bg = p.diff_change_bg })
  hl("DiffDelete", { bg = p.diff_delete_bg })
  hl("DiffText", { bg = p.diff_text_bg, bold = true })

  -- Legacy syntax groups
  hl("Comment", { fg = p.comment, italic = true })
  hl("Constant", { fg = p.yellow })
  hl("String", { fg = p.green })
  hl("Character", { fg = p.green })
  hl("Number", { fg = p.yellow })
  hl("Boolean", { fg = p.yellow })
  hl("Float", { fg = p.yellow })
  hl("Identifier", { fg = p.fg })
  hl("Function", { fg = p.blue })
  hl("Statement", { fg = p.orange })
  hl("Conditional", { fg = p.orange })
  hl("Repeat", { fg = p.orange })
  hl("Label", { fg = p.red })
  hl("Operator", { fg = p.fg })
  hl("Keyword", { fg = p.orange })
  hl("Exception", { fg = p.orange })
  hl("PreProc", { fg = p.orange })
  hl("Include", { fg = p.orange })
  hl("Define", { fg = p.orange })
  hl("Macro", { fg = p.blue })
  hl("PreCondit", { fg = p.orange })
  hl("Type", { fg = p.yellow })
  hl("StorageClass", { fg = p.orange })
  hl("Structure", { fg = p.yellow })
  hl("Typedef", { fg = p.yellow })
  hl("Special", { fg = p.blue })
  hl("SpecialChar", { fg = p.cyan })
  hl("Tag", { fg = p.red })
  hl("Delimiter", { fg = p.fg })
  hl("SpecialComment", { fg = p.comment, italic = true })
  hl("Debug", { fg = p.red })
  hl("Underlined", { fg = p.blue, underline = true })
  hl("Ignore", { fg = p.comment })
  hl("Error", { fg = p.red, bold = true })
  hl("Todo", { fg = p.orange, bold = true })
  hl("Added", { fg = p.green })
  hl("Changed", { fg = p.yellow })
  hl("Removed", { fg = p.red })

  -- Treesitter standard captures
  hl("@variable", { fg = p.fg })
  hl("@variable.builtin", { fg = p.red })
  hl("@variable.parameter", { fg = p.fg })
  hl("@variable.parameter.builtin", { fg = p.red })
  hl("@variable.member", { fg = p.red })
  hl("@constant", { fg = p.yellow })
  hl("@constant.builtin", { fg = p.yellow })
  hl("@constant.macro", { fg = p.yellow })
  hl("@module", { fg = p.fg })
  hl("@module.builtin", { fg = p.red })
  hl("@label", { fg = p.blue })
  hl("@string", { fg = p.green })
  hl("@string.documentation", { fg = p.green, italic = true })
  hl("@string.regexp", { fg = p.cyan })
  hl("@string.escape", { fg = p.cyan })
  hl("@string.special", { fg = p.cyan })
  hl("@string.special.symbol", { fg = p.yellow })
  hl("@string.special.path", { fg = p.cyan })
  hl("@string.special.url", { fg = p.orange, underline = true })
  hl("@character", { fg = p.green })
  hl("@character.special", { fg = p.cyan })
  hl("@boolean", { fg = p.yellow })
  hl("@number", { fg = p.yellow })
  hl("@number.float", { fg = p.yellow })
  hl("@type", { fg = p.yellow })
  hl("@type.builtin", { fg = p.yellow })
  hl("@type.definition", { fg = p.yellow })
  hl("@attribute", { fg = p.yellow })
  hl("@attribute.builtin", { fg = p.yellow })
  hl("@property", { fg = p.red })
  hl("@function", { fg = p.blue })
  hl("@function.builtin", { fg = p.blue })
  hl("@function.call", { fg = p.blue })
  hl("@function.macro", { fg = p.blue })
  hl("@function.method", { fg = p.blue })
  hl("@function.method.call", { fg = p.blue })
  hl("@constructor", { fg = p.blue })
  hl("@operator", { fg = p.fg })
  hl("@keyword", { fg = p.orange })
  hl("@keyword.coroutine", { fg = p.orange })
  hl("@keyword.function", { fg = p.orange })
  hl("@keyword.operator", { fg = p.orange })
  hl("@keyword.import", { fg = p.orange })
  hl("@keyword.type", { fg = p.orange })
  hl("@keyword.modifier", { fg = p.orange })
  hl("@keyword.repeat", { fg = p.orange })
  hl("@keyword.return", { fg = p.orange })
  hl("@keyword.debug", { fg = p.orange })
  hl("@keyword.exception", { fg = p.orange })
  hl("@keyword.conditional", { fg = p.orange })
  hl("@keyword.conditional.ternary", { fg = p.orange })
  hl("@keyword.directive", { fg = p.orange })
  hl("@keyword.directive.define", { fg = p.orange })
  hl("@punctuation.delimiter", { fg = p.fg })
  hl("@punctuation.bracket", { fg = p.fg })
  hl("@punctuation.special", { fg = p.cyan })
  hl("@comment", { fg = p.comment, italic = true })
  hl("@comment.documentation", { fg = p.comment, italic = true })
  hl("@comment.error", { fg = p.red, bold = true })
  hl("@comment.warning", { fg = p.yellow })
  hl("@comment.todo", { fg = p.orange, bold = true })
  hl("@comment.note", { fg = p.blue })
  hl("@markup.strong", { fg = p.yellow, bold = true })
  hl("@markup.italic", { fg = p.orange, italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@markup.underline", { underline = true })
  hl("@markup.heading", { fg = p.red, bold = true })
  hl("@markup.heading.1", { fg = p.red, bold = true })
  hl("@markup.heading.2", { fg = p.orange, bold = true })
  hl("@markup.heading.3", { fg = p.yellow, bold = true })
  hl("@markup.heading.4", { fg = p.green, bold = true })
  hl("@markup.heading.5", { fg = p.blue, bold = true })
  hl("@markup.heading.6", { fg = p.magenta, bold = true })
  hl("@markup.quote", { fg = p.green, italic = true })
  hl("@markup.math", { fg = p.cyan })
  hl("@markup.link", { fg = p.blue })
  hl("@markup.link.label", { fg = p.blue })
  hl("@markup.link.url", { fg = p.orange, underline = true })
  hl("@markup.raw", { fg = p.green })
  hl("@markup.raw.block", { fg = p.green })
  hl("@markup.list", { fg = p.red })
  hl("@markup.list.checked", { fg = p.green })
  hl("@markup.list.unchecked", { fg = p.comment })
  hl("@diff.plus", { fg = p.green })
  hl("@diff.minus", { fg = p.red })
  hl("@diff.delta", { fg = p.yellow })

  -- Diagnostics
  hl("DiagnosticError", { fg = p.red })
  hl("DiagnosticWarn", { fg = p.yellow })
  hl("DiagnosticInfo", { fg = p.blue })
  hl("DiagnosticHint", { fg = p.cyan })
  hl("DiagnosticOk", { fg = p.green })
  hl("DiagnosticVirtualTextError", { fg = p.red, italic = true })
  hl("DiagnosticVirtualTextWarn", { fg = p.yellow, italic = true })
  hl("DiagnosticVirtualTextInfo", { fg = p.blue, italic = true })
  hl("DiagnosticVirtualTextHint", { fg = p.cyan, italic = true })
  hl("DiagnosticVirtualTextOk", { fg = p.green, italic = true })
  hl("DiagnosticVirtualLinesError", { fg = p.red, italic = true })
  hl("DiagnosticVirtualLinesWarn", { fg = p.yellow, italic = true })
  hl("DiagnosticVirtualLinesInfo", { fg = p.blue, italic = true })
  hl("DiagnosticVirtualLinesHint", { fg = p.cyan, italic = true })
  hl("DiagnosticVirtualLinesOk", { fg = p.green, italic = true })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = p.red })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = p.yellow })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = p.blue })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = p.cyan })
  hl("DiagnosticUnderlineOk", { undercurl = true, sp = p.green })
  hl("DiagnosticFloatingError", { fg = p.red })
  hl("DiagnosticFloatingWarn", { fg = p.yellow })
  hl("DiagnosticFloatingInfo", { fg = p.blue })
  hl("DiagnosticFloatingHint", { fg = p.cyan })
  hl("DiagnosticFloatingOk", { fg = p.green })
  hl("DiagnosticSignError", { fg = p.red })
  hl("DiagnosticSignWarn", { fg = p.yellow })
  hl("DiagnosticSignInfo", { fg = p.blue })
  hl("DiagnosticSignHint", { fg = p.cyan })
  hl("DiagnosticSignOk", { fg = p.green })
  hl("DiagnosticDeprecated", { strikethrough = true })
  hl("DiagnosticUnnecessary", { link = "Comment" })

  -- LSP
  hl("LspReferenceText", { bg = p.selection })
  hl("LspReferenceRead", { bg = p.selection })
  hl("LspReferenceWrite", { bg = p.selection })
  hl("LspReferenceTarget", { bg = p.hover })
  hl("LspInlayHint", { fg = p.comment, italic = true })
  hl("LspCodeLens", { fg = p.comment, italic = true })
  hl("LspCodeLensSeparator", { fg = p.border })
  hl("LspSignatureActiveParameter", { fg = p.blue, underline = true })
  hl("@lsp.type.class", { fg = p.yellow })
  hl("@lsp.type.struct", { fg = p.yellow })
  hl("@lsp.type.enum", { fg = p.yellow })
  hl("@lsp.type.enumMember", { fg = p.yellow })
  hl("@lsp.type.interface", { fg = p.yellow })
  hl("@lsp.type.parameter", { fg = p.fg })
  hl("@lsp.type.property", { fg = p.red })
  hl("@lsp.type.variable", { fg = p.fg })
  hl("@lsp.type.keyword", { fg = p.orange })
  hl("@lsp.type.namespace", { fg = p.red })
  hl("@lsp.type.function", { fg = p.blue })
  hl("@lsp.type.method", { fg = p.blue })
  hl("@lsp.type.macro", { fg = p.blue })
  hl("@lsp.type.decorator", { fg = p.yellow })
  hl("@lsp.mod.deprecated", { strikethrough = true })

  -- Plugin: GitSigns
  hl("GitSignsAdd", { fg = p.green })
  hl("GitSignsChange", { fg = p.yellow })
  hl("GitSignsDelete", { fg = p.red })

  -- Plugin: which-key
  hl("WhichKey", { fg = p.orange })
  hl("WhichKeyGroup", { fg = p.blue })
  hl("WhichKeyDesc", { fg = p.fg })
  hl("WhichKeySeparator", { fg = p.comment })
  hl("WhichKeyFloat", { bg = p.bg_float })

  -- Plugin: blink.cmp
  hl("BlinkCmpMenu", { fg = p.fg, bg = p.bg_float })
  hl("BlinkCmpMenuBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpMenuSelection", { bg = p.selection })
  hl("BlinkCmpLabel", { fg = p.fg })
  hl("BlinkCmpLabelMatch", { fg = p.blue, bold = true })
  hl("BlinkCmpKind", { fg = p.orange })
  hl("BlinkCmpGhostText", { fg = p.comment, italic = true })

  -- Plugin: snacks.nvim
  hl("SnacksPickerDir", { fg = p.comment })
  hl("SnacksPickerFile", { fg = p.fg })
  hl("SnacksPickerMatch", { fg = p.blue, bold = true })
  hl("SnacksPickerPrompt", { fg = p.blue })
  hl("SnacksIndent", { fg = p.bg_alt })
  hl("SnacksIndentScope", { fg = p.selection })

  -- Plugin: indent-blankline / ibl
  hl("IblIndent", { fg = p.bg_alt })
  hl("IblScope", { fg = p.selection })
end

return M
