-- Auto-generated from themes/core/catppuccin-mocha.yaml
-- Template: wezterm-theme-template v1
return {
  tab_bar = {
    background = "#3c3d50",
    active_bg = "#1e1e2e",
    active_fg = "#cdd6f4",
    inactive_bg = "#37384b",
    inactive_fg = "#a6adc8",
    inactive_hover_bg = "#393b4d",
    inactive_hover_fg = "#cdd6f4",
    edge = "#6c7086",
    new_tab_bg = "#3c3d50",
    new_tab_fg = "#a6adc8",
    new_tab_hover_bg = "#393b4d",
    new_tab_hover_fg = "#cdd6f4",
  },
  window_frame = {
    active_titlebar_bg = "#3c3d50",
    inactive_titlebar_bg = "#3c3d50",
    active_titlebar_fg = "#cdd6f4",
    inactive_titlebar_fg = "#a6adc8",
    active_titlebar_border_bottom = "#6c7086",
    inactive_titlebar_border_bottom = "#6c7086",
  },
  colors = {
    foreground = "#cdd6f4",
    background = "#1e1e2e",
    cursor_bg = "#f5e0dc",
    cursor_fg = "#11111b",
    cursor_border = "#f5e0dc",
    selection_fg = "#1e1e2e",
    selection_bg = "#9399b2",
    scrollbar_thumb = "#6c7086",
    split = "#6c7086",
    ansi = {
      "#45475a",
      "#f38ba8",
      "#a6e3a1",
      "#f9e2af",
      "#89b4fa",
      "#f5c2e7",
      "#94e2d5",
      "#a6adc8",
    },
    brights = {
      "#585b70",
      "#f38ba8",
      "#a6e3a1",
      "#fab387",
      "#b4befe",
      "#cba6f7",
      "#89dceb",
      "#bac2de",
    },
    tab_bar = {
      background = "#3c3d50",
      inactive_tab_edge = "#6c7086",
      active_tab = {
        bg_color = "#1e1e2e",
        fg_color = "#cdd6f4",
      },
      inactive_tab = {
        bg_color = "#37384b",
        fg_color = "#a6adc8",
      },
      inactive_tab_hover = {
        bg_color = "#393b4d",
        fg_color = "#cdd6f4",
      },
      new_tab = {
        bg_color = "#3c3d50",
        fg_color = "#a6adc8",
      },
      new_tab_hover = {
        bg_color = "#393b4d",
        fg_color = "#cdd6f4",
      },
    },
  },
}
