{
  config,
  flakeDirectory,
  themeExports,
  ...
}:

let
  mkSymlink = path: config.lib.file.mkOutOfStoreSymlink "${flakeDirectory}/modules/wezterm/${path}";
  generatedThemes = themeExports.mutableDirLink config.lib.file "wezterm";
  selectedTheme = ''
    -- Generated by Home Manager from modules.commonTheme.
    return require(${builtins.toJSON "themes.${config.modules.commonTheme}"})
  '';
in
{
  xdg.configFile = {
    "wezterm/wezterm.lua".source = mkSymlink "files/wezterm.lua";
    "wezterm/theme.lua".text = selectedTheme;
    "wezterm/themes".source = generatedThemes;
  };
}
