theme = "custom_onelight"

[editor]
true-color = true
color-modes = true
cursor-shape = { insert = "bar", normal = "block", select = "underline" }

[editor.lsp]
display-messages = true
display-inlay-hints = true
